# Generated by Django 5.2.7 on 2025-11-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhanas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymkhana',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='gymkhana',
            name='starts_at',
        ),
    ]
